trigger:
  branches:
    include:
      - main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> install all dependencies"
    npm install-ci-test
  displayName: installing npm

  #When main branch is updated, we want to deploy to marketplace

- bash: |
    git config --global user.email "$(GIT_USER)"
    git config --global user.name "$(GIT_EMAIL)"
    npm version patch
    git add -a
    git commit -m "version upgraded"
    echo git status
    git push --force origin
  displayName: Update vscode marketplace version
  env:
    ENV_GIT_USER: $(GIT_USER)
    ENV_GIT_EMAIL: $(GIT_EMAIL)

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'AZ-GH-NH'
    repositoryName: 'nhall97/sfdx-oss-snippets-extension'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- bash: |
    echo ">>> Publish"
    npm run deployToMarketplace
  displayName: Publish to Marketplace
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Agent.OS'], 'Linux'))
  env:
    VSCE_PAT: $(VSCE_PAT)
    DISPLAY: ':99.0'