trigger:
  branches:
    include:
      - main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> install all dependencies"
    npm install-ci-test
  displayName: installing npm

  #When main branch is updated and succeeds, we want to update version numer, then release to marketplace

- bash: |
    git config user.email $(GIT_MAIL)
    git config user.name $(GIT_USERNAME)
    git checkout main
    npm version patch
    git commit -am "package.json version updated [skip ci]"
    git push origin main 
  displayName: npm version patch
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Agent.OS'], 'Linux'))
  env:
    ENV_GIT_USER: $(GIT_USERNAME)
    ENV_GIT_EMAIL: $(GIT_EMAIL)

- bash: |
    echo ">>> Publish"
    npm run deployToMarketplace
  displayName: Publish to Marketplace
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Agent.OS'], 'Linux'))
  env:
    VSCE_PAT: $(VSCE_PAT)
    DISPLAY: ':99.0'